networks:
  internal:
    internal: true
  external:
    driver: bridge

volumes:
  potluck-sql-storage:

services:
  caddy:
    build:
      context: .
      dockerfile: caddy.Dockerfile
    ports:
      - "80:80"
    networks:
      - external
      - internal
    depends_on:
      - frontend
      - backend
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    networks:
      - internal
  backend:
    build: ./Backend
    networks:
      - internal
    depends_on:
      - database
    environment:
      ConnectionString: |
        Server=database;
        Database=Potluck;
        User Id=sa;
        Password=TheDatabasePasswordWeUseAndNoOneCanGuess12345;
        Trusted_Connection=False;
        TrustServerCertificate=True;
        MultipleActiveResultSets=true;
  database:
    image: mcr.microsoft.com/azure-sql-edge:latest
    networks:
      - internal
    volumes:
      - potluck-sql-storage:/var/opt/mssql
    environment:
      ACCEPT_EULA: 1
      MSSQL_SA_PASSWORD: "TheDatabasePasswordWeUseAndNoOneCanGuess12345"
      MSSQL_PID: Developer
      MSSQL_TELEMETRY_ENABLED: "FALSE"