/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Integer
         * Format: int32
         */
        "/users/{name}/eatingTotalPeopleWS_pub": number;
        /**
         * Integer
         * Format: int32
         */
        "/users/{name}/eatingTotalPeopleWS_sub": number;
        /** String */
        "/users/{name}/homeStatusWS_pub": string;
        /** String */
        "/users/{name}/homeStatusWS_sub": string;
        /** String */
        "/users/{name}/dietWS_pub": string;
        /** String */
        "/users/{name}/dietWS_sub": string;
        /** Boolean */
        "/houses/{name}/cookingUserWS_pub": boolean;
        /** String */
        "/houses/{name}/cookingUserWS_sub": string;
        /** String */
        "/houses/{name}/shoppingListWS_pub": string;
        /** String */
        "/houses/{name}/shoppingListWS_sub": string;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
