/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Integer
         * Format: int32
         */
        "/eatingTotal_pub": number;
        /** ValueForUserOfInteger */
        "/eatingTotal_sub": {
            User?: string;
            /** Format: int32 */
            Value?: number;
        };
        /** String */
        "/homeStatus_pub": string;
        /** ValueForUserOfString */
        "/homeStatus_sub": {
            User?: string;
            Value?: null | string;
        };
        /** Boolean */
        "/cooking_pub": boolean;
        /** String */
        "/cooking_sub": string;
        /** String */
        "/shoppingList_pub": string;
        /** String */
        "/shoppingList_sub": string;
        /** String */
        "/dietPreferences_pub": string;
        /** ValueForUserOfString */
        "/dietPreferences_sub": {
            User?: string;
            Value?: null | string;
        };
        /** String */
        "/houseName_pub": string;
        /** String */
        "/houseName_sub": string;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
