/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Integer
         * Format: int32
         */
        "/users/current/eatingTotalPeople_pub": number;
        /** ValueForUserOfInteger */
        "/users/current/eatingTotalPeople_sub": {
            user?: string;
            /** Format: int32 */
            value?: number;
        };
        /** String */
        "/users/current/homeStatus_pub": string;
        /** ValueForUserOfString */
        "/users/current/homeStatus_sub": {
            user?: string;
            value?: null | string;
        };
        /** String */
        "/users/current/diet_pub": string;
        /** ValueForUserOfString */
        "/users/current/diet_sub": {
            user?: string;
            value?: null | string;
        };
        /** Boolean */
        "/houses/current/users/cooking_pub": boolean;
        /** String */
        "/houses/current/users/cooking_sub": string;
        /** String */
        "/houses/current/name_pub": string;
        /** String */
        "/houses/current/name_sub": string;
        /** String */
        "/houses/current/shoppingList_pub": string;
        /** String */
        "/houses/current/shoppingList_sub": string;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
