name: Backend

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  unit_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Backend
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
  #    quality_test:
  #        uses: ./.github/workflows/qodana_code_quality.yml
  #        permissions:
  #            checks: write
  #            contents: write
  #            pull-requests: write
  end_to_end_test:
    needs:
      - unit_test
    #            - quality_test
    uses: ./.github/workflows/end_to_end.yml
  deploy:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    needs:
      - unit_test
      #            - quality_test
      - end_to_end_test
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6.9.0
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/potluck-backend:latest
          context: ./Backend
