name: ESLint

on:
  push:
  pull_request:

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install pnpm
        working-directory: ./Frontend
        run: npm install -g pnpm
      - name: Install dependencies
        working-directory: ./Frontend
        run: pnpm install
      - name: Run Code quality lint tests
        working-directory: ./Frontend
        run: pnpm npx eslint