name: End-to-end

on:
  workflow_run:
    workflows: [ "Unit Test" ]
    types:
      - completed
    branches:
      - main

permissions:
  actions: write

jobs:
  end_to_end:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: ahmadnassri/action-workflow-run-wait@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yaml"
      - name: Install pnpm
        working-directory: ./e2e-tests
        run: npm install -g pnpm
      - name: Install dependencies
        working-directory: ./e2e-tests
        run: pnpm install
      - name: Install Playwright Browsers
        working-directory: ./e2e-tests
        run: pnpm exec playwright install --with-deps
      - name: Run Playwright tests
        working-directory: ./e2e-tests
        run: pnpm exec playwright test
